mariadb:
  image: mariadb
  volumes:
    - ./mariadb:/var/lib/mysql
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=PASSWORD

postfix:
  image: fabianwe/postfix
  environment:
  - DB_PASSWORD=PASSWORD
  - MAIL_HOSTNAME=example.org
  links:
    - mariadb:mysql
  volumes:
      - ./postconf:/postconf
      - ./certs:/certs
  #   - ./mail.crt:/mail.crt
  #   - ./mail.key:/mail.key
  #   #- ./postfix:/etc/postfix
  #   #- ./dovecot:/etc/dovecot
  #   - ./vmail:/var/vmail
