mariadb:
  image: mariadb
  volumes:
    - ./mariadb:/var/lib/mysql
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=PASSWORD

postfix:
  image: fabianwe/postfix
  environment:
  - DB_PASSWORD=PASSWORD
  - MAIL_HOSTNAME=localhost.de
  - MESSAGE_SIZE_LIMIT=1000000
  links:
    - mariadb:mysql
  volumes:
      - ./postconf:/postconf
      - ./doveconf:/doveconf
      - ./certs:/certs
      - ./vmail:/var/vmail
      # - ./log:/var/log
      # - ./postfix_spool:/var/spool/postfix
      # TODO make the spool directory a volume too
